In [10]:
# импортирую необходимые библиотеки
import pandas as pd

Скачиваем модуль для того, чтобы прочитать xlsx или xls файл через pandas.
```
sudo apt install python3-openpyxl
```

# Считываем данные из файла Excel

In [11]:
# загружаем excel-файл в обьект DataFrame и выводим на экран
grades = pd.read_excel('data/grades.xlsx')
display(grades)

   Student ID Student name  Grade
0           1          Аня      8
1           2         Катя      9
2           3         Маша      7
3           4         Миша      4
4           5         Женя      8
5           6          Оля      9
6           7         Витя      8
7           8         Дима      7
8           9         Витя      5

# Считываение данных из файла по excel сыллке

In [12]:
# загружаем данные по ссылке
data = pd.read_excel('https://github.com/asaydn/test/raw/master/january.xlsx',\
skiprows=3)
# выводим DataFrame на экран
display(data)

      Location  Oranges  Apples  Bananas  Blueberries  Total
0      Toronto     7651    4422     8580         3679  24332
1  Los Angeles      273    2998     9890         7293  20454
2      Atlanta     3758    6752     4599         4149  19258
3     New York     4019    8796     8486         9188  30489

In [13]:
# выбираем лист из excel книги
data = pd.read_excel('data/grades.xlsx', sheet_name='ML')
# выводим обьект DataFrame на экран
display(data)
# читаем первый другой лист из той же книги
data = pd.read_excel('data/grades.xlsx', sheet_name='Maths')
display(data)

   Student ID Student name  Grade
0           1          Аня      7
1           2         Катя      5
2           3         Маша      9
3           4         Миша      8
4           5         Женя      9
5           6          Оля      9
6           7         Витя      7
7           8         Дима      4
8           9         Витя      5

   Student ID Student name  Grade
0           1          Аня      8
1           2         Катя      9
2           3         Маша      7
3           4         Миша      4
4           5         Женя      8
5           6          Оля      9
6           7         Витя      8
7           8         Дима      7
8           9         Витя      5

# Выгрузка данных из DataFrame в Excel-файл

In [14]:
# создадим Excel файл
grades.to_excel('data/grades_new.xlsx')

In [15]:
# передаем в метод название для единственного листа и не сохраняем индексы 
grades.to_excel('data/grades_new.xlsx', sheet_name='Example', index=False)